name: NSB_model
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ablang2=0.2.1=pyhd8ed1ab_0
  - alsa-lib=1.2.13=hb9d3cd8_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - beartype=0.19.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py313h46c70d0_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cairo=1.18.2=h3394656_1
  - cffi=1.17.1=py313hfab6e84_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.1=py313h06a4308_0
  - cpython=3.13.1=py313hd8ed1ab_105
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.11=py313h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - double-conversion=3.3.0=h59595ed_0
  - einops=0.8.0=pyhd8ed1ab_1
  - et_xmlfile=1.1.0=py313h06a4308_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py313h11186cd_3
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=10.2.0=h4bba637_0
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.30.0=py313h06a4308_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jedi=0.19.2=py313h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jupyter_client=8.6.0=py313h06a4308_0
  - jupyter_core=5.7.2=py313h06a4308_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libblas=3.9.0=26_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=26_linux64_openblas
  - libclang-cpp19.1=19.1.7=default_hb5137d0_0
  - libclang13=19.1.7=default_h9c6a7e4_0
  - libcups=2.3.3=h4637d8d_4
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=26_linux64_openblas
  - libllvm19=19.1.7=ha7bfdaf_0
  - liblzma=5.6.3=hb9d3cd8_1
  - libmpdec=4.0.0=h4bc722e_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.45=h943b412_0
  - libpq=17.2=h3b95a9b_1
  - libprotobuf=5.28.3=h6128344_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.48.0=hee588c1_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libtorch=2.5.1=cpu_generic_h50b3d77_9
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxgboost=3.0.2=cpu_h97e353d_0
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.13.5=h8d12d68_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py313h1b76d92_1
  - markupsafe=3.0.2=py313h8060acc_1
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - ncurses=6.5=h2d0b736_2
  - nest-asyncio=1.6.0=py313h06a4308_0
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.61.2=py313h50b8c88_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openpyxl=3.1.5=py313h5eee18b_1
  - openssl=3.5.1=h7b32b05_0
  - parso=0.8.4=py313h06a4308_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.3.1=pyh145f28c_2
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=3.10.0=py313h06a4308_0
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h5eee18b_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=3.0.2=cpu_pyhc5f55e3_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.15.1=py313h06a4308_1
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyside6=6.8.1=py313h5f61773_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.1=ha99a958_105_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.13=5_cp313
  - pyzmq=26.2.0=py313h6a678d5_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.1=h588cce1_2
  - readline=8.2=h8228510_1
  - rotary-embedding-torch=0.8.4=pyhe5570ce_0
  - scikit-learn=1.6.1=py313h8ef605b_0
  - scipy=1.15.1=py313h750cbce_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.7=h1b44611_2
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2022.1.0=h4ce085d_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py313h536fd9c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py313h06a4308_0
  - umap-learn=0.5.9.post2=py313h78bf25f_0
  - wayland=1.23.1=h3e06ad9_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xgboost=3.0.2=cpu_pyhc1a9e11_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xlsxwriter=3.2.5=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zeromq=4.3.5=h6a678d5_0
  - zstandard=0.23.0=py313h80202fe_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - antiberty==0.1.3
      - biopython==1.85
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - fair-esm==2.0.0
      - filelock==3.18.0
      - fonttools==4.58.5
      - fsspec==2025.5.1
      - huggingface-hub==0.27.1
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - networkx==3.5
      - numpy==2.3.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.2
      - seaborn==0.13.2
      - setuptools==80.9.0
      - sympy==1.14.0
      - tokenizers==0.21.0
      - torch==2.7.1
      - transformers==4.48.0
      - triton==3.3.1
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
